### PR TITLE
Remove popularity field

### PR DESCRIPTION
**Pull request by barthalion**
It used to be available via v1 API, but it has changed in AUR 4.1.0.
It is hardly useful anyway; switch to v4 would require way more changes.

### CODE REVIEW

**Comment by barthalion** [comment]
Given my experience with Python and nose (that is close to zero), I don't think I'll be able to fix the tests, but you get the idea… You can easily see the disappearance of popularity field [here](https://aur.archlinux.org/rpc.php?type=info&arg=fzf).

**Comment by cdown** [comment]
"Popularity" seems to be very recently removed, it was definitely there within the last week.

Thanks for the report, I'll look into this in the next few days and fix the tests (basically, you just need to remove references to "popularity" in the samples).

**Comment by cdown** [comment]
Fix is now in develop, with tests passing. Thanks!

**Comment by cdown** [comment]
New version 0.11.0 released with fix.

**Comment by rmarquis** [comment]
Why has this field be removed? It has been added in AUR4 and RPCv4, and is still available in the latest RPCv5.

It is the category field that has been removed in AUR4.

**Comment by cdown** [comment]
"popularity" also disappeared for a time. It was definitely gone when this issue was opened. Maybe they added it back in again?

**Comment by rmarquis** [comment]
Unlikely. I'm receiving emails from the aur-dev mailing list, and never read anything about the removal of that field.

I'm pretty sure OP made an error and confused it with the category field, as the popularity field has not been introduced with the RPCv1, but has been implemented much later.

Edit: Ah, I see this project still uses the RPCv1. Afaik, backward compatibility is kept and new features are only introduced in new versions. Any plan to move to the latest RPC version?

**Comment by cdown** [comment]
I guess I'm not up to date with new developments. :-)

I've created #27.

**Comment by rmarquis** [comment]
Thanks! Sorry for the confusion, I really thought this project was using RPCv4 already.

**Pull request closed without merging**
