### PR TITLE
Don't error on invalid package.

### PR DESCRIPTION
**Pull request by ghost**
Fixes the `info` function to return `None` when a package doesn't exist instead of returning an error.

### CODE REVIEW

**Comment by cdown** [comment]
Looks good to me, although a test case for that would be good.

**Comment by ghost** [comment]
Alright, added a test.

**Comment by cdown** [comment]
Should be as part of test-query, but meh. test-utils shouldn't be calling out to live anyway, I thought I'd got rid of that. I will look at it soon, refactor it, and merge. Thanks for the patch.

**Comment by ghost** [comment]
Ah, well, I tried, I guess.

**Comment by cdown** [comment]
Patch to old unmergeable code

**Pull request closed without merging**
